name: Deploy automatically to development environment
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
        env:
          REACT_APP_AUTH_GW_BASE_URL: ${{ secrets.AUTH_GW_BASE_URL }}
          REACT_APP_USER_API_BASE_URL: ${{ secrets.USER_API_BASE_URL }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: build/
          retention-days: 2

  deploy:
    name: Deploy to S3
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: Application_Artifact
          path: ./public/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install dependencies
        run: npm ci
        working-directory: ./infra
      - name: Set artifact path in Pulumi config
        working-directory: ./infra
        run: pulumi config -s virtualfinland/dev set artifactPath ../public/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Run Pulumi deployment
        uses: pulumi/actions@v3
        with:
          work-dir: ./infra
          command: up
          stack-name: virtualfinland/dev
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

