name: Deploy automatically to development environment
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: auth-gw url from Pulumi
        uses: Virtual-Finland-Development/pulumi-outputs-action@v1
        id: auth-gw-url
        with:
          organization: virtualfinland
          project: authentication-gw
          stack: dev
          resource: endpoint
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: users-api url from Pulumi
        uses: Virtual-Finland-Development/pulumi-outputs-action@v1
        id: users-api-url
        with:
          organization: virtualfinland
          project: users-api
          stack: dev
          resource: ApplicationUrl
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: testbed-api url from Pulumi
        uses: Virtual-Finland-Development/pulumi-outputs-action@v1
        id: testbed-api-url
        with:
          organization: virtualfinland
          project: testbed-api
          stack: dev
          resource: url
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: codesets url from Pulumi
        if: ${{ inputs.environment }}
        uses: Virtual-Finland-Development/pulumi-outputs-action@v1
        id: codesets-url
        with:
          organization: virtualfinland
          project: codesets
          stack: ${{ inputs.environment }}
          resource: url
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Build application
        run: npm run build
        env:
          REACT_APP_AUTH_GW_BASE_URL: ${{ steps.auth-gw-url.outputs.resource-output }}
          REACT_APP_USERS_API_BASE_URL: ${{ steps.users-api-url.outputs.resource-output }}
          REACT_APP_TESTBED_API_BASE_URL: ${{ steps.testbed-api-url.outputs.resource-output }}
          REACT_APP_CODESETS_BASE_URL: ${{ steps.codesets-url.outputs.resource-output }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Application_Artifact
          path: build/
          retention-days: 2

  deploy:
    name: Deploy to S3
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: Application_Artifact
          path: ./public/
      - name: Install dependencies
        run: npm ci
        working-directory: ./infra
      - name: Set artifact path in Pulumi config
        working-directory: ./infra
        run: pulumi config -s virtualfinland/dev set artifactPath ../public/
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: dev
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Run Pulumi deployment
        uses: pulumi/actions@v4
        with:
          work-dir: ./infra
          command: up
          stack-name: virtualfinland/dev
          upsert: true
